### ISSUE TITLE
ngen-cal updates required for this tutorial to work

### ISSUE THREAD

**Issue by hellkite500** [hellkite500/ubiquitous-doodle#1]
- [ ] noaa-owp/ngen-cal#128
- [ ] noaa-owp/ngen-cal#129
- [ ] noaa-owp/ngen-cal#130
